### ISSUE TITLE
Multiple-GOPATH-workspaces support

### ISSUE THREAD

**Issue by RonAmihai** [ricardo-ch/mockery-intellij-plugin#2]
The plugin doesn't seem to support GOPATH which includes multiple workspaces 
(Example: "path1;path2" on Windows, "path1:path2" on Unix).

Mockery itself seems to support this feature, and I think this support [is important](https://dmitri.shuralyov.com/blog/18).

Anyway, thanks for the nice plugin, it works well with regular single-workspace GOPATH.

**Comment by RonAmihai** [comment]
I've  implemented this support. I'll be happy if you'll consider to add it: 

`
{{ GenMockeryActionHandler, starts from line 99}}

        // Do the generation
		Path filePath = Paths.get(FileDocumentManager.getInstance().getFile(editor.getDocument()).getCanonicalPath());
		GeneralCommandLine commandLine = PtyCommandLine.isEnabled() ? new PtyCommandLine() : new GeneralCommandLine();
		commandLine.withWorkDirectory(filePath.getParent().toString());

		String[] envGoPaths = EnvironmentUtil.getValue("GOPATH").split(File.pathSeparator);
		String mockeryPath = "";
		for (String goPath : envGoPaths) {
			File goPathBin = new File(goPath + "/bin");
			if(!goPathBin.exists() || !goPathBin.isDirectory())
				continue;

			String[] goPathBinFiles = goPathBin.list();
			if(goPathBinFiles == null)
				continue;

			for(String goPathBinExecutable : goPathBinFiles)
				if(goPathBinExecutable.startsWith("mockery.")) {
					mockeryPath = new File(goPath + "/bin/mockery").getAbsolutePath();
					break;
				}
		}
		
		if(mockeryPath.isEmpty()) {
			HintManager.getInstance().showErrorHint(editor, "Mockery executable wasn't found in GOPATH");
			return;
		}
		commandLine.setExePath(mockeryPath);
		// End of feature implementation . . .

        	StringJoiner joiner = new StringJoiner("|");
		// ...
`

**Comment by cmeury** [comment]
@RonAmihai Awesome! Would you be willing to create a PR for this so the maintainers can try it out?

**Comment by RonAmihai** [comment]
@cmeury Done. I'll happy if someone can review my request.

**Comment by peppelan** [comment]
Resolved with #3.
Version `1.1.0` of the plugin, containing the change, is being released
